### PR TITLE
feat(DAO): abstract list data to collections

### PR DESCRIPTION
**Pull request by rneillj**
Just verified this works. Making a PR so that you can test with the data you have before refactoring the other identical calls.

### CODE REVIEW

**Comment by chriscantu** [comment]
@censhin PR Looks good to me.  I am just curious why Mercurial was added as a dependency.

**Comment by rneillj** [comment]
@chriscantu It was added, because I had to install it when setting it up on Mac OS X.

**Comment by chriscantu** [comment]
@censhin I totally forgot about that. Thanks!

IForgot

**Comment by chriscantu** [comment]
LGTM... MERGE IT!

MergeIt

**Pull request merged**
